
$script = <<-SCRIPT
echo I am provisioning...
apk add docker
addgroup vagrant docker
rc-update add docker boot
service docker start
apk add docker-compose
docker info
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/alpine-3.14"
	config.vm.box_version = "20210723.0.1"
  config.vm.provision "shell", inline: $script
  config.vm.boot_timeout = 600

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    config.vm.define "m1" do |m1|
      m1.vm.hostname ="m1"
      m1.vm.network "private_network", ip: "10.0.0.10" , hostname: true
      m1.vm.network "forwarded_port", guest: 8080, host: 8080
      m1.vm.network "forwarded_port", guest: 8000, host: 8000
    end
  
    config.vm.define "m2" do |m2|
      m2.vm.hostname ="m2"
      m2.vm.network "private_network", ip: "10.0.0.11", hostname: true
    end

    config.vm.define "m3" do |m3|
      m3.vm.hostname ="m3"
      m3.vm.network "private_network", ip: "10.0.0.12", hostname: true
    end

    config.vm.define "w1" do |w1|
      w1.vm.hostname ="w1"
      w1.vm.network "private_network", ip: "10.0.0.13", hostname: true
    end

    config.vm.define "w2" do |w2|
      w2.vm.hostname ="w2"
      w2.vm.network "private_network", ip: "10.0.0.14", hostname: true
    end

    config.vm.define "w3" do |w3|
      w3.vm.hostname ="w3"
      w3.vm.network "private_network", ip: "10.0.0.15", hostname: true
    end

  end
  