FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine
COPY . /app
WORKDIR /home
ENV DOTNET_ROLL_FORWARD="Major"
ENV PATH ="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef --version 5.0.9

WORKDIR /app
RUN ["dotnet", "build"]
ENV ASPNETCORE_URLS=http://+:80  
EXPOSE 80/tcp
RUN chmod +x ./entrypoint.sh
CMD /bin/sh ./entrypoint.sh